//NAV ACTION TYPES
export const TOGGLE_SIDENAV = 'TOGGLE_SIDENAV';
//USER ACTION TYPES
//register
export const REGISTER_ATTEMPT = 'REGISTER_ATTEMPT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE'; 
export const REGISTER_BUTTON_TOGGLE = 'REGISTER_BUTTON_TOGGLE';
//login
export const LOGIN_ATTEMPT = 'LOGIN_ATTEMPT';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_BUTTON_TOGGLE = 'LOGIN_BUTTON_TOGGLE';
//logout
export const LOGOUT_ACCOUNT='LOGOUT_ACCOUNT';
//update account
export const UPDATE_ACCOUNT_ATTEMPT='UPDATE_ACCOUNT_ATTEMPT';
export const UPDATE_ACCOUNT_SUCCESS='UPDATE_ACCOUNT_SUCCESS';
export const UPDATE_ACCOUNT_FAILURE='UPDATE_ACCOUNT_FAILURE';
//user fields
export const USERNAME_CHANGED = 'USERNAME_CHANGED';
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';
export const EMAIL_CHANGED = 'EMAIL_CHANGED';
export const BIRTH_DATE_CHANGED = 'BIRTH_DATE_CHANGED';
export const USER_PICTURE_UPLOAD_ATTEMPT = 'ATTEMPT_USER_PICTURE_UPLOAD';
export const USER_PICTURE_CHANGED_SUCCESS = 'USER_PICTURE_CHANGED_SUCCESS';
export const USER_PICTURE_CHANGED_FAILURE = 'USER_PICTURE_CHANGED_FAILURE';
export const USER_PICTURE_CHANGED = 'USER_PICTURE_CHANGED';
export const USER_FIRST_NAME_CHANGED = 'USER_FIRST_NAME_CHANGED';
export const USER_LAST_NAME_CHANGED = 'USER_LAST_NAME_CHANGED';
export const CANCEL_UPLOAD_PROFILE = 'CANCEL_UPLOAD_PROFILE';
export const RESET_USER_STATUS_MESSAGE = 'RESET_USER_STATUS_MESSAGE';
//account fields
export const AUTH_FAILED='AUTH_FAILED';
export const GET_ACCOUNT_ATTEMPT='GET_ACCOUNT_ATTEMPT';
export const GET_ACCOUNT_FAILED='GET_ACCOUNT_FAILED';
export const GET_ACCOUNT_SUCCESS='GET_ACCOUNT_SUCCESS';
export const EDIT_ACCOUNT='EDIT_ACCOUNT';
export const CLOSE_EDIT_ACCOUNT='CLOSE_EDIT_ACCOUNT';
//SEARCH ACTION TYPES
//search fields
export const SEARCH_FIELD_CHANGED = 'SEARCH_FIELD_CHANGED';
export const SEARCH_CATEGORY_CHANGED = 'SEARCH_CATEGORY_CHANGED';
export const SEARCH_ATTEMPT = 'SEARCH_ATTEMPT';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAIL = 'SEARCH_FAIL';
//COMICS ACTION TYPES
export const GET_COMICS_ATTEMPT = 'GET_COMICS_ATTEMPT';
export const GET_COMICS_FAILURE = 'GET_COMICS_FAILURE';
export const GET_COMICS_SUCCESS = 'GET_COMICS_SUCCESS';
export const GET_COMIC_ATTEMPT = 'GET_COMIC_ATTEMPT';
export const GET_COMIC_SUCCESS = 'GET_COMIC_SUCCESS';
export const GET_COMIC_FAILURE = 'GET_COMIC_FAILURE';
export const ADD_COMIC_ATTEMPT = 'GET_COMIC_ATTEMPT';
export const ADD_COMIC_FAILURE = 'GET_COMIC_FAILURE';
export const ADD_COMIC_SUCCESS = 'GET_COMIC_SUCCESS';
export const COMIC_TITLE_CHANGED='COMIC_TITLE_CHANGED';
export const COMIC_UPC_CHANGED='COMIC_UPC_CHANGED';
export const COMIC_DESCRIPTION_CHANGED='COMIC_DESCRIPTION_CHANGED';
export const COMIC_FIVE_DIGIT_ID_CHANGED='COMIC_FIVE_DIGIT_ID_CHANGED';
export const COMIC_CONDITION_CHANGED='COMIC_CONDITION_CHANGED';
export const COMIC_PUBLISHER_CHANGED='COMIC_PUBLISHER_CHANGED';
export const COMIC_CREATORS_CHANGED='COMIC_CREATORS_CHANGED';
export const COMIC_IMAGE_CHANGED_ATTEMPT='COMIC_IMAGE_CHANGED_ATTEMPT';
export const COMIC_IMAGE_CHANGED_SUCCESS='COMIC_IMAGE_CHANGED_SUCCESS';
export const COMIC_IMAGE_CHANGED_FAILURE='COMIC_IMAGE_CHANGED_FAILURE';
export const UPDATE_COMIC_ATTEMPT='UPDATE_COMIC_ATTEMPT';
export const UPDATE_COMIC_SUCCESS='UPDATE_COMIC_SUCCESS';
export const UPDATE_COMIC_FAILURE='UPDATE_COMIC_FAILURE';
export const DELETE_COMIC_ATTEMPT='DELETE_COMIC_ATTEMPT';
export const DELETE_COMIC_SUCCESS='DELETE_COMIC_SUCCESS';
export const DELETE_COMIC_FAILURE='DELETE_COMIC_FAILURE';
export const GET_COMIC_CONDITIONS_ATTEMPT='GET_COMIC_CONDITIONS_ATTEMPT';
export const GET_COMIC_CONDITIONS_FAILURE='GET_COMIC_CONDITIONS_FAILURE';
export const GET_COMIC_CONDITIONS_SUCCESS='GET_COMIC_CONDITIONS_SUCCESS';