//USER ACTION TYPES
//register
export const REGISTER_ATTEMPT = 'REGISTER_ATTEMPT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE'; 
export const REGISTER_BUTTON_TOGGLE = 'REGISTER_BUTTON_TOGGLE';
//login
export const LOGIN_ATTEMPT = 'LOGIN_ATTEMPT';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_BUTTON_TOGGLE = 'LOGIN_BUTTON_TOGGLE';
//user fields
export const USERNAME_CHANGED = 'USERNAME_CHANGED';
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';
export const EMAIL_CHANGED = 'EMAIL_CHANGED';
export const BIRTH_DATE_CHANGED = 'BIRTH_DATE_CHANGED';
export const BIRTH_MONTH_CHANGED = 'BIRTH_MONTH_CHANGED';
export const BIRTH_YEAR_CHANGED = 'BIRTH_YEAR_CHANGED';
export const USER_PICTURE_CHANGED = 'USER_PICTURE_CHANGED';
export const USER_FIRST_NAME_CHANGED = 'USER_FIRST_NAME_CHANGED';
export const USER_LAST_NAME_CHANGED = 'USER_LAST_NAME_CHANGED';