//NAV ACTION TYPES
export const TOGGLE_SIDENAV = 'TOGGLE_SIDENAV';
//USER ACTION TYPES
//register
export const REGISTER_ATTEMPT = 'REGISTER_ATTEMPT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE'; 
export const REGISTER_BUTTON_TOGGLE = 'REGISTER_BUTTON_TOGGLE';
//login
export const LOGIN_ATTEMPT = 'LOGIN_ATTEMPT';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_BUTTON_TOGGLE = 'LOGIN_BUTTON_TOGGLE';
//user fields
export const USERNAME_CHANGED = 'USERNAME_CHANGED';
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';
export const EMAIL_CHANGED = 'EMAIL_CHANGED';
export const BIRTH_DATE_CHANGED = 'BIRTH_DATE_CHANGED';
export const USER_PICTURE_UPLOAD_ATTEMPT = 'ATTEMPT_USER_PICTURE_UPLOAD';
export const USER_PICTURE_CHANGED_SUCCESS = 'USER_PICTURE_CHANGED_SUCCESS';
export const USER_PICTURE_CHANGED_FAILURE = 'USER_PICTURE_CHANGED_FAILURE';
export const USER_PICTURE_CHANGED = 'USER_PICTURE_CHANGED';
export const USER_FIRST_NAME_CHANGED = 'USER_FIRST_NAME_CHANGED';
export const USER_LAST_NAME_CHANGED = 'USER_LAST_NAME_CHANGED';
export const CANCEL_UPLOAD_PROFILE = 'CANCEL_UPLOAD_PROFILE';
export const RESET_USER_STATUS_MESSAGE = 'RESET_USER_STATUS_MESSAGE';
//SEARCH ACTION TYPES
//search fields
export const SEARCH_FIELD_CHANGED = 'SEARCH_FIELD_CHANGED';
export const SEARCH_CATEGORY_CHANGED = 'SEARCH_CATEGORY_CHANGED';
export const SEARCH_ATTEMPT = 'SEARCH_ATTEMPT';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAIL = 'SEARCH_FAIL';
//COMICS ACTION TYPES
export const GET_COMIC_ATTEMPT = 'GET_COMIC_ATTEMPT';
export const GET_COMIC_SUCCESS = 'GET_COMIC_SUCCESS';
export const GET_COMIC_FAILURE = 'GET_COMIC_FAILURE';